### ISSUE TITLE
输出中文乱码

### ISSUE THREAD

**Issue by ivysrono** [hex2010/sgf2gif#1]
不知道作者还维护不~
一直用multigo记谱，最近发现了Sabaki也可以用来记谱，就把multigo扔了。然后又发现了你这个项目，但是原来的谱信息都写在注释里，输出光溜溜的，于是手动把黑白、日期什么的补上，然后就再输出发现人名乱码了。然后开始测试，发现在 Sabaki-File-Game Info 里手动输入棋手中文姓名，用你这项目输出的就会乱码。
![default](https://user-images.githubusercontent.com/2649544/38453294-be912bc6-3a85-11e8-80e6-82dbaba382df.png)
![default](https://user-images.githubusercontent.com/2649544/38453312-14657b10-3a86-11e8-8930-6f2d71ce14ef.png)
![default](https://user-images.githubusercontent.com/2649544/38453308-ff95beca-3a85-11e8-9b24-ddf314cb44e0.gif)

这棋谱是我用最新版的[Sabaki](https://github.com/SabakiHQ/Sabaki/releases)＋[LeelaSabaki](https://github.com/SabakiHQ/LeelaSabaki/releases)＋[leela-zero](https://github.com/gcp/leela-zero/releases)左右互搏出来的，黑白双方本来都是英文，是我手动改了测试的。
[乱码测试.zip](https://github.com/hex2010/sgf2gif/files/1886219/default.zip)

**Comment by hex2010** [comment]
这程序只能处理国标码棋谱， 你传的棋谱是utf-8， 就乱码了。这问题不难解决，我抽空改。

**Comment by hex2010** [comment]
加了识别字符编码的功能。 因为手头棋谱很少， 所以没怎么测试， 但bin里面的谱以及 issue1，2的谱都测试通过了。 
commit ad0ead7b7c7bcae8be16c7888bcbddc96f4ad230

**Comment by ivysrono** [comment]
#5
