### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by ivysrono** [hex2010/sgf2gif#2]
Win10 x64

https://github.com/hex2010/sgf2gif/blob/master/bin/sgf2gif.exe

[崩溃测试.zip](https://github.com/hex2010/sgf2gif/files/1886221/default.zip)

![default](https://user-images.githubusercontent.com/2649544/38453318-5b4a3a2a-3a86-11e8-9323-edea8135563a.png)

和 #1 那个谱一样，是LeelaZera自我对战生成的，但那个就不崩溃……

**Comment by hex2010** [comment]
commit ad0ead7b7c7bcae8be16c7888bcbddc96f4ad230
