### ISSUE TITLE
无中生有的后续几百步

### ISSUE THREAD

**Issue by ivysrono** [hex2010/sgf2gif#3]
[原谱.zip](https://github.com/hex2010/sgf2gif/files/1899120/default.zip)
[后面几百步是哪冒出来的鬼.zip](https://github.com/hex2010/sgf2gif/files/1899121/default.zip)

**Comment by ivysrono** [comment]
新版似乎不能重现这个问题了，可喜可贺。

**Comment by hex2010** [comment]
我也发现了， 那可能是和之前是同一个BUG。 

commit ad0ead7b7c7bcae8be16c7888bcbddc96f4ad230
