### ISSUE TITLE
棋谱打开失败

### ISSUE THREAD

**Issue by ivysrono** [hex2010/sgf2gif#4]
新版exe

[fail2open.sgf.zip](https://github.com/hex2010/sgf2gif/files/1915363/fail2open.zip)

![default](https://user-images.githubusercontent.com/2649544/38810610-e0baefe4-41b9-11e8-8a4e-6960a49f4cf9.png)

**Comment by hex2010** [comment]
原因是“）”之前的换行未处理。已修复。

commit 1f2f8680a24959bc5f1585c31b7883fa14776e5a
