### ISSUE TITLE
新版的奇怪标题逻辑

### ISSUE THREAD

**Issue by ivysrono** [hex2010/sgf2gif#5]
只要name里有内容，就只显示name不显示黑白胜负了。
#1 的文件：
![default](https://user-images.githubusercontent.com/2649544/38811157-7541e50e-41bb-11e8-8ce4-2843daa5079c.png)
![default](https://user-images.githubusercontent.com/2649544/38811210-8ca751c0-41bb-11e8-9594-665623ebab34.gif)

**Comment by ivysrono** [comment]
备份：该问题已经于 #4 顺带解决，从主楼编辑至此，存档备查。
还有一个生成了极为奇怪的标题：
[奇怪标题.zip](https://github.com/hex2010/sgf2gif/files/1915420/default.zip)
![default](https://user-images.githubusercontent.com/2649544/38811763-0c167dfe-41bd-11e8-9f0f-a83b37a498b0.gif)

**Comment by hex2010** [comment]
乱码是因为有一段处理国标码的代码被误用在 UTF-8上了， 已修复。

Name是SGF的GN字段，Game Name，也就是是标题吧，似无不妥？ 

commit b8cdd0f0e24dcd183d6d65a19ba82b7357a343b3

**Comment by ivysrono** [comment]
我想保留对弈双方信息与胜负肿么办
要不给个选项？

**Comment by hex2010** [comment]
一个棋谱可显示的信息太多了， 比如贴目，规则和赛事， 甚至还有注解什么的。除非都做成选项， 否则总是众口难调。你要用Name记录什么内容呢？ 不如自己把棋手和胜负填在Name里吧，还可以填其他内容， 想填什么就填什么。

**Comment by ivysrono** [comment]
也对，谢谢。
顺便请教个问题，event本意是填什么内容？

**Comment by hex2010** [comment]
event应该是赛事，填“xx届农心杯”这样的

**Comment by ivysrono** [comment]
谢谢
